/**
 * Free tier data loader — Model C-refined.
 * JSON files generated by scripts/extract-free-data.js (do not edit by hand).
 * Combines Glossary + Vocab N5 Vol.1 + Grammar N5 + Kanji N5 = 661 entries.
 */

import glossaryRaw from './glossary.json';
import grammarN5Raw from './grammar-n5.json';
import kanjiN5Raw from './kanji-n5.json';
import vocabN5Vol1Raw from './vocab-n5-vol1.json';

import type { ContentType, CsvRow, Deck, Entry, JlptLevel } from './types';

function buildEntries(
  rows: CsvRow[],
  type: ContentType,
  level: JlptLevel | null,
  deckId: string,
): Entry[] {
  return rows.map((r) => ({
    id: `${deckId}-${r.no}`,
    type,
    level,
    no: r.no,
    t: r.t,
    d: r.d,
    p: r.p,
    e: r.e,
  }));
}

const glossaryEntries   = buildEntries(glossaryRaw   as CsvRow[], 'glossary', null, 'glossary');
const vocabN5Vol1Entries = buildEntries(vocabN5Vol1Raw as CsvRow[], 'vocab',    'N5', 'vocab-n5-vol1');
const grammarN5Entries  = buildEntries(grammarN5Raw  as CsvRow[], 'grammar',  'N5', 'grammar-n5');
const kanjiN5Entries    = buildEntries(kanjiN5Raw    as CsvRow[], 'kanji',    'N5', 'kanji-n5');

const ALL_ENTRIES: Entry[] = [
  ...glossaryEntries,
  ...vocabN5Vol1Entries,
  ...grammarN5Entries,
  ...kanjiN5Entries,
];

/** Free decks (Model C-refined N5 Starter Set) + locked stubs for upsell. */
export const decks: Deck[] = [
  { id: 'kanji-n5',       type: 'kanji',    level: 'N5', title: 'Kanji · N5',       entryCount: kanjiN5Entries.length,   isFree: true },
  { id: 'grammar-n5',     type: 'grammar',  level: 'N5', title: 'Grammar · N5',     entryCount: grammarN5Entries.length, isFree: true },
  { id: 'vocab-n5-vol1',  type: 'vocab',    level: 'N5', title: 'Vocab · N5 Vol.1', entryCount: vocabN5Vol1Entries.length, isFree: true },
  { id: 'glossary',       type: 'glossary', level: null, title: 'Glossary',         entryCount: glossaryEntries.length,  isFree: true },

  /* Locked upsell — paid SKUs (no entries embedded, link to landing) */
  { id: 'vocab-n5-vol2',  type: 'vocab',    level: 'N5', title: 'Vocab · N5 Vol.2', entryCount: 0, isFree: false },
  { id: 'vocab-n4-vol1',  type: 'vocab',    level: 'N4', title: 'Vocab · N4 Vol.1', entryCount: 0, isFree: false },
  { id: 'kanji-n4',       type: 'kanji',    level: 'N4', title: 'Kanji · N4',       entryCount: 0, isFree: false },
  { id: 'grammar-n4',     type: 'grammar',  level: 'N4', title: 'Grammar · N4',     entryCount: 0, isFree: false },
];

export function entriesForDeck(deckId: string): Entry[] {
  return ALL_ENTRIES.filter((e) => e.id.startsWith(`${deckId}-`));
}

export const TOTAL_FREE_ENTRIES = ALL_ENTRIES.length;
