/**
 * Free tier data loader — Model C-refined, per-pack split.
 * JSON file generated by scripts/extract-free-data.js (do not edit by hand).
 * 31 decks (1 per CSV pack) · 661 entries.
 */

import freeTier from './free-tier.json';

import type { Deck, Entry, FreeTierData } from './types';

const data = freeTier as unknown as FreeTierData;

/** All free decks, flagged isFree=true. Paid decks moved to /shop (fetch from Supabase). */
const freeDecks: Deck[] = data.decks.map((d) => ({ ...d, isFree: true }));

export const decks: Deck[] = freeDecks;

export function entriesForDeck(deckId: string): Entry[] {
  const rows = data.entries[deckId];
  if (!rows) return [];
  const deck = freeDecks.find((d) => d.id === deckId);
  if (!deck) return [];
  return rows.map((r) => ({
    id: `${deck.pack}-${r.no}`,
    type: deck.type,
    level: deck.level,
    pack: deck.pack,
    tags: deck.tags,
    no: r.no,
    t: r.t,
    d: r.d,
    p: r.p,
    e: r.e,
  }));
}

export const TOTAL_FREE_ENTRIES = freeDecks.reduce((s, d) => s + d.entryCount, 0);
